### ISSUE TITLE
关于保存QQ数据

### ISSUE THREAD

**Issue by TimeRainStarSky** [yuuki-nya/chronocat-docker#1]
可以通过-v把QQ数据映射出来？目前不清楚QQ数据有哪些，作者可以试试

**Comment by yuuki-nya** [comment]
数据文件应该是在`/home/user/.config/QQ`， 我尝试过映射，但是容器重建后QQ还是要求登陆，应该是设备信息发生了变化，或者等其他大佬来指点下

**Comment by yuuki-nya** [comment]
https://github.com/yuuki-nya/chronocat-docker/commit/1717e49a6238b4de352ba323b3df1881d53a3bd3 已经实现了
