### ISSUE TITLE
可以用环境变量设置vnc的密码

### ISSUE THREAD

**Issue by ZGLinus** [yuuki-nya/chronocat-docker#2]
`docker-cli` 或者 `docker-compose` 的环境变量会覆盖 `Dockerfile` 里面的同名环境变量，所以可以把命令 `x11vnc -storepasswd $VNC_PASSWD ~/.vnc/passwd` 放进启动脚本，这样用户就可以完成用环境变量设置vnc密码了。

另外，可以用 [noVNC](https://github.com/novnc/noVNC) 把远程桌面放进浏览器里面，只需要克隆两个仓库， [noVNC](https://github.com/novnc/noVNC) 和 [websockify](https://github.com/novnc/websockify)，再加一行命令就可以了。

最后，有一个简单思路但是做法复杂的固化数据的方法，就是把会更新的文件放在 host 而不是 container 里面，具体可以查看我的 [fork](https://github.com/ZGLinus/chronocat-docker)。

**Comment by yuuki-nya** [comment]
非常感谢思路和代码，现在已经更新了docker环境设置VNC密码和增加了noVNC

至于数据固化这块，配合 docker-compose-plugin 是挺好，但考虑到使用本repo还有可能只用docker run或者想快速体验，就暂时不采取你的做法了，毕竟这玩意build一次挺费时的

**Comment by ZGLinus** [comment]
指出一个小小的问题，novnc的地址应该是 `http://ip:port/vnc.html`

**Comment by yuuki-nya** [comment]
> 指出一个小小的问题，novnc的地址应该是 `http://ip:port/vnc.html`

不需要了，我修改了index就是vnc.html
